name: Django CI/CD for sneakers
on:
  push:
    branches: [ "main", "staging" ]
  pull_request:
    branches: [ "main", "staging"]
jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run: 
        working-directory: backend
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
        pip-compile requirements.in
        pip install -r requirements.txt

    - name: Test with pre-commit
      run: pre-commit run -a 

          
